// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241031205707_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PiscineModel", b =>
                {
                    b.Property<int>("ID_UEV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_UEV"));

                    b.Property<string>("ADRESSE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ARRONDISSE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EQUIPEME")
                        .HasColumnType("longtext");

                    b.Property<string>("GESTION")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("LAT")
                        .HasColumnType("float");

                    b.Property<float>("LONG")
                        .HasColumnType("float");

                    b.Property<string>("NOM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("POINT_X")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("POINT_Y")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PROPRIETE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TYPE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID_UEV");

                    b.ToTable("PiscineModels");
                });
#pragma warning restore 612, 618
        }
    }
}
